# config/packages/nelmio_cors.yaml

nelmio_cors:
    paths:
        '^/': ~
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
